### Feature Enginnering with Univariate Statistical Test ( Chi-square for Classification)

In [1]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2


In [2]:
# Load the dataset
dname = 'pima-indians-diabetes.data.csv'
features = ['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe = read_csv(dname, names = features)
array = dataframe.values

X = array[:,0:8]
Y = array[:,8]

In [3]:
# feature Extraction

test = SelectKBest(score_func=chi2, k=4)
fit  = test.fit(X,Y)

In [4]:
# Summarize Scores
set_printoptions(precision=3)
print(fit.scores_)


[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [9]:
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [5]:
best_features = fit.transform(X)

In [6]:
best_features

array([[148. ,   0. ,  33.6,  50. ],
       [ 85. ,   0. ,  26.6,  31. ],
       [183. ,   0. ,  23.3,  32. ],
       ...,
       [121. , 112. ,  26.2,  30. ],
       [126. ,   0. ,  30.1,  47. ],
       [ 93. ,   0. ,  30.4,  23. ]])

In [7]:
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [8]:
best_features

array([[148. ,   0. ,  33.6,  50. ],
       [ 85. ,   0. ,  26.6,  31. ],
       [183. ,   0. ,  23.3,  32. ],
       ...,
       [121. , 112. ,  26.2,  30. ],
       [126. ,   0. ,  30.1,  47. ],
       [ 93. ,   0. ,  30.4,  23. ]])

## Recursive Feature elimination

In [10]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression


In [11]:
# Load Data
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

In [12]:
# feature extraction
model = LogisticRegression()
rfe  =RFE(model)
fit = rfe.fit(X,Y)

C:\Users\chira\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [13]:
#Num of features 

fit.n_features_

4

In [16]:
#fit.feature_names_in_

In [17]:
fit.support_

array([ True,  True, False, False, False,  True,  True, False])

In [18]:
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [19]:
fit.ranking_

array([1, 1, 3, 4, 5, 1, 1, 2])

## Feature Importance using Decision Trees

In [21]:
# Feature importance with Extra Trees Classifier

from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier



In [22]:
#load data

filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

In [29]:
# Feature extraction 
model = DecisionTreeClassifier(criterion = 'gini',random_state =0)
model.fit(X,Y)
print(model.feature_importances_)

[0.062 0.334 0.08  0.018 0.039 0.222 0.128 0.118]
