In [3]:
import numpy as np
import pandas as pd

from matplotlib import pyplot as plt
from sklearn.cluster import KMeans


In [43]:
univ = pd.read_csv("C:/Users/chira/Downloads/Universities.csv")
univ

Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0          Brown  1310     89      22       13     22704        94
1        CalTech  1415    100      25        6     63575        81
2            CMU  1260     62      59        9     25026        72
3       Columbia  1310     76      24       12     31510        88
4        Cornell  1280     83      33       13     21864        90
5      Dartmouth  1340     89      23       10     32162        95
6           Duke  1315     90      30       12     31585        95
7     Georgetown  1255     74      24       12     20126        92
8        Harvard  1400     91      14       11     39525        97
9   JohnsHopkins  1305     75      44        7     58691        87
10           MIT  1380     94      30       10     34870        91
11  Northwestern  1260     85      39       11     28052        89
12     NotreDame  1255     81      42       13     15122        94
13     PennState  1081     38      54       18     10185        80
14     Princeton  1375     91      14        8     30220        95
15        Purdue  1005     28      90       19      9066        69
16      Stanford  1360     90      20       12     36450        93
17      TexasA&M  1075     49      67       25      8704        67
18    UCBerkeley  1240     95      40       17     15140        78
19      UChicago  1290     75      50       13     38380        87
20     UMichigan  1180     65      68       16     15470        85
21         UPenn  1285     80      36       11     27553        90
22           UVA  1225     77      44       14     13349        92
23    UWisconsin  1085     40      69       15     11857        71
24          Yale  1375     95      19       11     43514        96

In [44]:
# Normalization function
from sklearn.preprocessing  import StandardScaler
scaler = StandardScaler()

scaled_univ= scaler.fit_transform(univ.iloc[:,1:])

scaled_univ


array([[ 0.41028362,  0.6575195 , -0.88986682,  0.07026045, -0.33141256,
         0.82030265],
       [ 1.39925928,  1.23521235, -0.73465749, -1.68625071,  2.56038138,
        -0.64452351],
       [-0.06065717, -0.76045386,  1.02438157, -0.93346022, -0.16712136,
        -1.65863393],
       [ 0.41028362, -0.02520842, -0.78639393, -0.18066972,  0.29164871,
         0.14422904],
       [ 0.12771914,  0.34241431, -0.32076595,  0.07026045, -0.39084607,
         0.36958691],
       [ 0.69284809,  0.6575195 , -0.83813038, -0.68253005,  0.33778044,
         0.93298158],
       [ 0.4573777 ,  0.71003703, -0.47597528, -0.18066972,  0.29695528,
         0.93298158],
       [-0.10775125, -0.13024348, -0.78639393, -0.18066972, -0.51381683,
         0.59494478],
       [ 1.25797704,  0.76255456, -1.30375836, -0.43159988,  0.85874344,
         1.15833946],
       [ 0.36318954, -0.07772595,  0.24833493, -1.43532055,  2.21481798,
         0.0315501 ],
       [ 1.06960072,  0.92010716, -0.47597528, -0.

In [45]:
# Find the optimal cluster

range(1,4)

range(1, 4)

In [46]:
for i in range(1,4):
    print(i)

1
2
3


In [47]:
# Create the cluster algorithm 

from sklearn.cluster import KMeans
cluster_new = KMeans(3, random_state = 42)
cluster_new.fit(scaled_univ)

KMeans(n_clusters=3, random_state=42)

In [48]:
cluster_new.labels_

array([2, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 1, 0, 1, 0, 1, 2, 2, 2, 2,
       2, 1, 0])

In [49]:
# Assign the clusters to the OG dataset

univ['clusterid_new'] = cluster_new.labels_

In [50]:
univ.head()

Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate  clusterid_new
0     Brown  1310     89      22       13     22704        94              2
1   CalTech  1415    100      25        6     63575        81              0
2       CMU  1260     62      59        9     25026        72              2
3  Columbia  1310     76      24       12     31510        88              2
4   Cornell  1280     83      33       13     21864        90              2

In [51]:
cluster_new.cluster_centers_

array([[ 0.90738779,  0.73921344, -0.76914845, -0.76617344,  0.97562148,
         0.61998454],
       [-1.93029211, -1.98148647,  1.59348244,  1.63857398, -1.23359906,
        -1.68680366],
       [-0.03711013,  0.10608541,  0.04570052,  0.02843875, -0.32051642,
         0.09727948]])

In [52]:
univ.groupby('clusterid_new').agg(['mean'])

SAT      Top10     Accept    SFRatio      Expenses  \
                      mean       mean       mean       mean          mean   
clusterid_new                                                               
0              1362.777778  90.555556  24.333333   9.666667  41176.888889   
1              1061.500000  38.750000  70.000000  19.250000   9953.000000   
2              1262.500000  78.500000  40.083333  12.833333  22858.000000   

                GradRate  
                    mean  
clusterid_new             
0              92.222222  
1              71.750000  
2              87.583333

In [60]:
univ[univ['clusterid_new']==0].sort_values(by=['SFRatio'],ascending=True)

Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate  \
1        CalTech  1415    100      25        6     63575        81   
9   JohnsHopkins  1305     75      44        7     58691        87   
14     Princeton  1375     91      14        8     30220        95   
5      Dartmouth  1340     89      23       10     32162        95   
10           MIT  1380     94      30       10     34870        91   
8        Harvard  1400     91      14       11     39525        97   
24          Yale  1375     95      19       11     43514        96   
6           Duke  1315     90      30       12     31585        95   
16      Stanford  1360     90      20       12     36450        93   

    clusterid_new  
1               0  
9               0  
14              0  
5               0  
10              0  
8               0  
24              0  
6               0  
16              0